criado testes para us e feito refatorações
douglashiura/us-uid pull request #2
Opened 2018-12-12 13:18 UTC by AdanDuM

2019-01-25 20:27 UTC, douglashiura requested changes

2019-01-25 20:27 UTC, douglashiura commented on tools/us+tests/.project
> +</projectDescription>
Colocar um git ignore no pasta  tools/us+tests/bin

2019-01-25 20:27 UTC, douglashiura commented on tools/us+tests/tests/tests/br/ufsc/leb/adangomes/us/ScenarioFromUTest.java
> +//	@Test(expected = Exception.class)
Estes testes comentados são necessários

2019-01-26 02:03 UTC, AdanDuM commented on tools/us+tests/tests/tests/br/ufsc/leb/adangomes/us/ScenarioFromUTest.java
> +//	@Test(expected = Exception.class)
Tinha esquecido de descomentar isso. Vou arrumar!

2019-01-26 13:05 UTC, merged